#ifndef LUFIA2_SYSTEM_WRAM_H
#define LUFIA2_SYSTEM_WRAM_H

/* Generated from metadata/memory_map.toml; edit the map. */

/* memory-map:begin (scripts/metadata_index.py) */
/* Direct page; D = 0 in the field loop. */
#define DP_FRAME_COUNTER 0x42u
#define DP_BUTTONS_HELD 0x46u
#define DP_BUTTONS_PRESSED 0x4au
#define DP_NMI_STUB 0x67u
#define DP_NMI_UPLOAD_FLAGS 0x73u
#define DP_PROBE_X 0x8fu
#define DP_PROBE_Y 0x91u
#define DP_ACTOR_SLOT 0xa7u
#define DP_SLOT_WORD_OFFSET 0xa9u
#define DP_SLOT_RECORD_OFFSET 0xabu

/* Low WRAM $7E:0100-$7E:1FFF, reached through the bank-$00 mirror. */
#define WRAM_CGRAM_BUFFER 0x0320u
#define WRAM_CGRAM_BUFFER_COUNT 256u
#define WRAM_FADE_CONTROL 0x0581u
#define WRAM_FADE_LEVEL 0x0582u
#define WRAM_BRIGHTNESS 0x0583u
#define WRAM_FIELD_MAP_ID 0x05acu
#define WRAM_FIELD_FLAGS 0x05b5u
#define WRAM_FIELD_REQUESTS 0x05b7u
#define WRAM_UNK_7E05D2 0x05d2u
#define WRAM_UNK_7E05D2_COUNT 40u
#define WRAM_ACTOR_ID 0x05fau
#define WRAM_ACTOR_ID_COUNT 40u
#define WRAM_ACTOR_STATE 0x0622u
#define WRAM_ACTOR_STATE_COUNT 40u
#define WRAM_OBJECT_STATE 0x064au
#define WRAM_OBJECT_STATE_COUNT 32u
#define WRAM_UNK_7E066A 0x066au
#define WRAM_UNK_7E066A_COUNT 40u
#define WRAM_ACTOR_TILE_X 0x06bau
#define WRAM_ACTOR_TILE_X_COUNT 40u
#define WRAM_ACTOR_TILE_Y 0x06e2u
#define WRAM_ACTOR_TILE_Y_COUNT 40u
#define WRAM_UNK_7E0736 0x0736u
#define WRAM_UNK_7E0736_COUNT 40u
#define WRAM_EVENT_FLAGS 0x077eu
#define WRAM_TEXT_STATE 0x099bu
#define WRAM_FOLLOW_SLOTS 0x09a1u
#define WRAM_FOLLOW_SLOTS_COUNT 5u
#define WRAM_WINDOW_MODE 0x09a7u
#define WRAM_FIELD_TRANSITION_FLAGS 0x09aau
#define WRAM_BATTLE_SCRIPT_CONTEXT 0x0a13u
#define WRAM_BATTLE_PARTY_RECORDS 0x0a64u
#define WRAM_BATTLE_PARTY_RECORDS_COUNT 4u
#define WRAM_BATTLE_CAPSULE_RECORD 0x0a6cu
#define WRAM_BATTLE_ENEMY_RECORDS 0x0a6eu
#define WRAM_BATTLE_ENEMY_RECORDS_COUNT 6u
#define WRAM_GOLD 0x0a8au
#define WRAM_BATTLE_BACKGROUND_ID 0x11e1u
#define WRAM_BATTLE_CONTROL_FLAGS 0x11e7u
#define WRAM_FIELD_LAYER_SCROLL_X 0x121eu
#define WRAM_FIELD_LAYER_SCROLL_X_COUNT 4u
#define WRAM_FIELD_LAYER_SCROLL_Y 0x1226u
#define WRAM_FIELD_LAYER_SCROLL_Y_COUNT 4u
#define WRAM_SCREEN_EFFECTS 0x1261u
#define WRAM_PALETTE_FADE 0x1262u
#define WRAM_BATTLE_WAIT_COUNTER 0x1264u
#define WRAM_TEXT_WAIT_ACTOR 0x1269u
#define WRAM_UNK_7E1291 0x1291u
#define WRAM_UNK_7E1291_COUNT 40u
#define WRAM_BATTLE_STATUS_ICON_RECORDS 0x1479u
#define WRAM_BATTLE_STATUS_ICON_RECORDS_COUNT 5u
#define WRAM_BATTLE_ICON_STATUS_MASK 0x148du
#define WRAM_BATTLE_ICON_PERIOD 0x148eu
#define WRAM_BATTLE_ICON_STATE 0x148fu
#define WRAM_BATTLE_ICON_SPRITE_OFFSET 0x1491u
#define WRAM_BATTLE_PARTY_COUNT 0x153cu
#define WRAM_BATTLE_PARTY_IDS 0x153du
#define WRAM_BATTLE_PARTY_IDS_COUNT 4u
#define WRAM_BATTLE_CURSOR_ENABLED 0x15d7u
#define WRAM_BATTLE_CURSOR_SOURCE 0x15d8u
#define WRAM_BATTLE_CURSOR_COUNT 0x15dau
#define WRAM_BATTLE_RESULT_WINDOW 0x15f3u
#define WRAM_BATTLE_EXPERIENCE_REWARD 0x1605u
#define WRAM_BATTLE_GOLD_REWARD 0x1608u
#define WRAM_BATTLE_ITEM_REWARD 0x160bu
#define WRAM_ANIMATION_MASK 0x17aau
#define WRAM_SOUND_COMMAND 0x17acu
#define WRAM_BATTLE_STAGED_ACTION 0x1b7fu
#define WRAM_BATTLE_TURN_QUEUE 0x1b8cu
#define WRAM_BATTLE_TURN_QUEUE_COUNT 12u
#define WRAM_BATTLE_PARTY_TARGETS 0x1bb0u
#define WRAM_BATTLE_PARTY_TARGETS_COUNT 5u
#define WRAM_BATTLE_ENEMY_TARGETS 0x1bc8u
#define WRAM_BATTLE_ENEMY_TARGETS_COUNT 6u
#define WRAM_BATTLE_PARTY_SLOT 0x1be8u

/* Long WRAM addresses. */
#define WRAM_FIELD_LAYER_CELL_BASE 0x7fd008u
#define WRAM_FIELD_LAYER_CELL_BASE_COUNT 4u
#define WRAM_FIELD_LAYER_WIDTH 0x7fd010u
#define WRAM_FIELD_LAYER_WIDTH_COUNT 4u
#define WRAM_FIELD_LAYER_HEIGHT 0x7fd018u
#define WRAM_FIELD_LAYER_HEIGHT_COUNT 4u
#define WRAM_FIELD_METATILE_BASE 0x7fd03cu
#define WRAM_FIELD_ALTERNATE_METATILE_BASE 0x7fd040u
#define WRAM_FIELD_PENDING_OBJECT_X 0x7fd046u
#define WRAM_FIELD_PENDING_OBJECT_Y 0x7fd047u
#define WRAM_FIELD_OBJECT_HEIGHT 0x7fd04du
#define WRAM_FIELD_OBJECT_FLAGS 0x7fd05fu
#define WRAM_UNK_7FD0A1 0x7fd0a1u
#define WRAM_FIELD_CLAIMED_ACTOR_IDS 0x7fd0a2u
#define WRAM_FIELD_CLAIMED_ACTOR_IDS_COUNT 2u
#define WRAM_FIELD_OBJECT_PALETTE_POINTER 0x7fd0a4u
#define WRAM_FIELD_MOSAIC_STATE 0x7fd0f2u
#define WRAM_FIELD_MOSAIC_ACCUMULATOR 0x7fd0f3u
#define WRAM_UNK_7FD0FE 0x7fd0feu
#define WRAM_FIELD_EVENT_BASE 0x7fd194u
#define WRAM_FIELD_EVENT_BASE_BANK 0x7fd196u
#define WRAM_FIELD_MAP_RECORD_BYTE7 0x7fd2a6u
#define WRAM_FIELD_MAP_RECORD_BYTE7_COUNT 224u
#define WRAM_FIELD_MAP_RECORD_BYTE8 0x7fd386u
#define WRAM_FIELD_MAP_RECORD_BYTE8_COUNT 224u
#define WRAM_FIELD_EVENT_CALL_RECORDS 0x7fd466u
#define WRAM_FIELD_EVENT_CALL_RECORDS_COUNT 32u
#define WRAM_ACTOR_DISPLAY_OFFSET_X 0x7fdc8cu
#define WRAM_ACTOR_DISPLAY_OFFSET_X_COUNT 40u
#define WRAM_ACTOR_DISPLAY_OFFSET_Y 0x7fdd1cu
#define WRAM_ACTOR_DISPLAY_OFFSET_Y_COUNT 40u
#define WRAM_ACTOR_FINE_X 0x7fddaeu
#define WRAM_ACTOR_FINE_X_COUNT 40u
#define WRAM_ACTOR_FINE_Y 0x7fde3eu
#define WRAM_ACTOR_FINE_Y_COUNT 40u
#define WRAM_OBJECT_SCRIPT 0x7fdeeeu
#define WRAM_OBJECT_SCRIPT_COUNT 32u
#define WRAM_UNK_7FE216 0x7fe216u
#define WRAM_UNK_7FE316 0x7fe316u
#define WRAM_UNK_7FE316_COUNT 40u
#define WRAM_ACTOR_SECONDARY_TIMER 0x7fe35eu
#define WRAM_ACTOR_SECONDARY_TIMER_COUNT 40u
#define WRAM_ACTOR_PRIMARY_TIMER 0x7fe3c6u
#define WRAM_ACTOR_PRIMARY_TIMER_COUNT 40u
#define WRAM_ACTOR_SECONDARY_SCRIPT 0x7fe3eeu
#define WRAM_ACTOR_SECONDARY_SCRIPT_COUNT 40u
#define WRAM_ACTOR_WALK_COUNTER 0x7fe48eu
#define WRAM_ACTOR_WALK_COUNTER_COUNT 40u
#define WRAM_ACTOR_PRIMARY_SCRIPT 0x7fe506u
#define WRAM_ACTOR_PRIMARY_SCRIPT_COUNT 40u
#define WRAM_CAVE_MAP_HEADER_POINTER 0x7fe6a5u
#define WRAM_CAVE_MAP_HEADER_BANK 0x7fe6a7u
#define WRAM_CAVE_HEADER_ROOM_POINT_COUNT 0x7fe731u
#define WRAM_CAVE_HEADER_OBJECT_COUNT 0x7fe734u
/* memory-map:end */

/* $0583 values. */
#define BRIGHTNESS_FULL 0x0fu
#define BRIGHTNESS_FORCED_BLANK 0x80u

#endif
