format = 1
rom = "lufia2-usa"

[[symbol]]
address = "80:8E9D"
name = "Lufia2DecompressResourceFile"
kind = "function"
status = "identified"

[[symbol]]
address = "83:BB93"
name = "Lufia2UpdateActorSlots"
kind = "function"
status = "draft"

[[symbol]]
address = "83:BBF3"
name = "Lufia2PlayerSlotSpecialUpdate"
kind = "function"
status = "verified"

[[symbol]]
address = "83:C1B4"
name = "Lufia2PlayerSlotStandardUpdate"
kind = "function"
status = "identified"

[[symbol]]
address = "83:C7F8"
name = "Lufia2ActorPrimaryUpdate"
kind = "function"
status = "draft"

[[symbol]]
address = "83:D508"
name = "Lufia2ActorSecondaryUpdate"
kind = "function"
status = "draft"
