#ifndef LUFIA2_CAVE_WRAM_H
#define LUFIA2_CAVE_WRAM_H

/* Ancient Cave WRAM, DB-relative; _LONG adds bank $7F. */
enum {
    CAVE_FLOOR = 0xe696u,
    CAVE_ROOM_GRID = 0xea00u,
    CAVE_SHAPE_GRID = 0xeb00u,
    CAVE_OBJECT_COUNT = 0xe731u,
    CAVE_CHEST_COUNT = 0xe734u,
    CAVE_OBJECT_COLUMNS = 0xe6b1u,
    CAVE_OBJECT_ROWS = 0xe6d1u,
    CAVE_OBJECT_SIZES = 0xe216u,
    CAVE_CHEST_COLUMNS = 0xe736u,
    CAVE_CHEST_ROWS = 0xe73eu,
    CAVE_START_COLUMN = 0xe6a9u,
    CAVE_START_ROW = 0xe6aau,
    CAVE_STAIR_COLUMN = 0xe6abu,
    CAVE_STAIR_ROW = 0xe6acu,

    CAVE_FLOOR_LONG = 0x7f0000u | CAVE_FLOOR,
    CAVE_ROOM_GRID_LONG = 0x7f0000u | CAVE_ROOM_GRID,
    CAVE_SHAPE_GRID_LONG = 0x7f0000u | CAVE_SHAPE_GRID,
    CAVE_OBJECT_COUNT_LONG = 0x7f0000u | CAVE_OBJECT_COUNT,
    CAVE_CHEST_COUNT_LONG = 0x7f0000u | CAVE_CHEST_COUNT,
    CAVE_OBJECT_COLUMNS_LONG = 0x7f0000u | CAVE_OBJECT_COLUMNS,
    CAVE_START_COLUMN_LONG = 0x7f0000u | CAVE_START_COLUMN,
    CAVE_START_ROW_LONG = 0x7f0000u | CAVE_START_ROW,
    CAVE_STAIR_COLUMN_LONG = 0x7f0000u | CAVE_STAIR_COLUMN,
    CAVE_STAIR_ROW_LONG = 0x7f0000u | CAVE_STAIR_ROW,

    /* Sizes of the room and shape grids (16 x 16 cells). */
    CAVE_GRID_BYTES = 0x0100,
    CAVE_BLANK_SHAPE_PAIR = 0x1c1c,

    /* Item selection: a table of record pointers in bank $96 whose records
     * hold the fields below, and the two lists it sorts them into. */
    ITEM_RECORD_BANK = 0x96,
    ITEM_RECORD_TABLE = 0xcf69,
    ITEM_RECORD_TABLE_BYTES = 0x03a4,
    ITEM_RECORD_FLAGS = 0,
    ITEM_RECORD_FLAGS2 = 1,
    ITEM_RECORD_PRICE = 5,
    ITEM_RECORD_USE = 7,
    ITEM_FLAG_FIELD_USABLE = 0x02,
    ITEM_FLAG_EXCLUDED = 0x20,
    ITEM_USE_LIST_B = 0x0001,
    CAVE_ITEM_LISTS_LONG = 0x7f0000,
    CAVE_ITEM_LIST_B_BASE = 0x1000,
    CAVE_UNLIMITED_PRICE_FLOOR = 0x3c,
    CAVE_PRICE_PER_FLOOR = 1000,
    CAVE_DP_LIST_A_END = 0x5d,
    CAVE_DP_PRICE_LIMIT = 0x54,
    CAVE_DP_LIST_B_END = 0x60,

    /* Chest contents: eight words from $7F:E746, filled from the lists above and
     * the ROM tables below. */
    CAVE_CHEST_WORDS = 0xe746,
    CAVE_CHEST_WORD_BYTES = 0x0010,
    CAVE_ITEM_LISTS = 0x0000,
    CAVE_STORY_CHEST_STATE = 0xe75d,
    CAVE_STORY_CHEST_SEEN_LONG = 0x7fe75e,
    CAVE_SCROLL_CHEST_STATE_LONG = 0x7fe75b,
    CAVE_STORY_CHEST_PLACED = 0x80,
    CAVE_STORY_CHEST_ODDS = 0x05,
    CAVE_STORY_CHEST_KINDS = 0x09,
    CAVE_STORY_FLAG_BASE = 0xc8,
    CAVE_STORY_CHEST_ITEMS = 0x91ffca,
    CAVE_CHEST_ITEM_MARK = 0x0200,
    CAVE_SCROLL_CHEST_FLOOR_LIMIT = 0x15,
    CAVE_SCROLL_CHEST_CHANCE = 0x3c,
    CAVE_SCROLL_CHEST_WORD = 0x022d,
    CAVE_COMMON_ITEM_TABLE = 0x91ffdc,
    CAVE_COMMON_ITEM_COUNT = 0x09,
    CAVE_EQUIPMENT_TABLE = 0x94eea0,
    CAVE_EQUIPMENT_COUNT = 0x29,
    CAVE_CHEST_EQUIPMENT_MARK = 0x40,
    CAVE_CONSUMABLE_TABLE = 0x94f13d,
    CAVE_CONSUMABLE_COUNT = 0x1f,
    CAVE_SPELL_COUNT = 0x23,
    CAVE_SPELL_CHEST_MARK = 0x80,
    CAVE_ROLL_LIST_A = 0xae,
    CAVE_ROLL_LIST_B = 0x81,
    CAVE_ROLL_SPELL = 0x63,
    CAVE_ROLL_EQUIPMENT = 0x5e,
    CAVE_ROLL_COMMON = 0x24,
    CAVE_DP_CHEST_KIND = 0x58,
    CAVE_DP_CHEST_BIT = 0x55,

    CAVE_DP_TILE_COLUMN = 0x8f,
    CAVE_DP_TILE_ROW = 0x91,
};

#endif
