#ifndef LUFIA2_CAVE_WRAM_H
#define LUFIA2_CAVE_WRAM_H

#include "system/wram.h"

/* Ancient Cave WRAM, DB-relative; _LONG adds bank $7F. */
enum {
    CAVE_FLOOR = 0xe696u,
    CAVE_ROOM_GRID = 0xea00u,
    CAVE_SHAPE_GRID = 0xeb00u,
    CAVE_OBJECT_COUNT = 0xe731u,
    CAVE_CHEST_COUNT = 0xe734u,
    CAVE_OBJECT_COLUMNS = 0xe6b1u,
    CAVE_OBJECT_ROWS = 0xe6d1u,
    CAVE_OBJECT_SIZES = 0xe216u,
    CAVE_CHEST_COLUMNS = 0xe736u,
    CAVE_CHEST_ROWS = 0xe73eu,
    CAVE_START_COLUMN = 0xe6a9u,
    CAVE_START_ROW = 0xe6aau,
    CAVE_STAIR_COLUMN = 0xe6abu,
    CAVE_STAIR_ROW = 0xe6acu,

    CAVE_FLOOR_LONG = 0x7f0000u | CAVE_FLOOR,
    CAVE_ROOM_GRID_LONG = 0x7f0000u | CAVE_ROOM_GRID,
    CAVE_SHAPE_GRID_LONG = 0x7f0000u | CAVE_SHAPE_GRID,
    CAVE_OBJECT_COUNT_LONG = 0x7f0000u | CAVE_OBJECT_COUNT,
    CAVE_CHEST_COUNT_LONG = 0x7f0000u | CAVE_CHEST_COUNT,
    CAVE_OBJECT_COLUMNS_LONG = 0x7f0000u | CAVE_OBJECT_COLUMNS,
    CAVE_OBJECT_ROWS_LONG = 0x7f0000u | CAVE_OBJECT_ROWS,
    CAVE_CHEST_COLUMNS_LONG = 0x7f0000u | CAVE_CHEST_COLUMNS,
    CAVE_CHEST_ROWS_LONG = 0x7f0000u | CAVE_CHEST_ROWS,
    CAVE_START_COLUMN_LONG = 0x7f0000u | CAVE_START_COLUMN,
    CAVE_START_ROW_LONG = 0x7f0000u | CAVE_START_ROW,
    CAVE_STAIR_COLUMN_LONG = 0x7f0000u | CAVE_STAIR_COLUMN,
    CAVE_STAIR_ROW_LONG = 0x7f0000u | CAVE_STAIR_ROW,

    /* Sizes of the room and shape grids (16 x 16 cells). */
    CAVE_GRID_BYTES = 0x0100,
    CAVE_BLANK_SHAPE_PAIR = 0x1c1c,

    /* Item selection: a table of record pointers in bank $96 whose records
     * hold the fields below, and the two lists it sorts them into. */
    ITEM_RECORD_BANK = 0x96,
    ITEM_RECORD_TABLE = 0xcf69,
    ITEM_RECORD_TABLE_BYTES = 0x03a4,
    ITEM_RECORD_FLAGS = 0,
    ITEM_RECORD_FLAGS2 = 1,
    ITEM_RECORD_PRICE = 5,
    ITEM_RECORD_USE = 7,
    ITEM_FLAG_FIELD_USABLE = 0x02,
    ITEM_FLAG_EXCLUDED = 0x20,
    ITEM_USE_LIST_B = 0x0001,
    CAVE_ITEM_LISTS_LONG = 0x7f0000,
    CAVE_ITEM_LIST_B_BASE = 0x1000,
    CAVE_UNLIMITED_PRICE_FLOOR = 0x3c,
    CAVE_PRICE_PER_FLOOR = 1000,
    CAVE_DP_LIST_A_END = 0x5d,
    CAVE_DP_PRICE_LIMIT = 0x54,
    CAVE_DP_LIST_B_END = 0x60,

    /* Chest contents: eight words from $7F:E746, filled from the lists above and
     * the ROM tables below. */
    CAVE_CHEST_WORDS = 0xe746,
    CAVE_CHEST_WORD_BYTES = 0x0010,
    CAVE_ITEM_LISTS = 0x0000,
    CAVE_STORY_CHEST_STATE = 0xe75d,
    CAVE_STORY_CHEST_SEEN_LONG = 0x7fe75e,
    CAVE_SCROLL_CHEST_STATE_LONG = 0x7fe75b,
    CAVE_STORY_CHEST_PLACED = 0x80,
    CAVE_STORY_CHEST_ODDS = 0x05,
    CAVE_STORY_CHEST_KINDS = 0x09,
    CAVE_STORY_FLAG_BASE = 0xc8,
    CAVE_STORY_CHEST_ITEMS = 0x91ffca,
    CAVE_CHEST_ITEM_MARK = 0x0200,
    CAVE_SCROLL_CHEST_FLOOR_LIMIT = 0x15,
    CAVE_SCROLL_CHEST_CHANCE = 0x3c,
    CAVE_SCROLL_CHEST_WORD = 0x022d,
    CAVE_COMMON_ITEM_TABLE = 0x91ffdc,
    CAVE_COMMON_ITEM_COUNT = 0x09,
    CAVE_EQUIPMENT_TABLE = 0x94eea0,
    CAVE_EQUIPMENT_COUNT = 0x29,
    CAVE_CHEST_EQUIPMENT_MARK = 0x40,
    CAVE_CONSUMABLE_TABLE = 0x94f13d,
    CAVE_CONSUMABLE_COUNT = 0x1f,
    CAVE_SPELL_COUNT = 0x23,
    CAVE_SPELL_CHEST_MARK = 0x80,
    CAVE_ROLL_LIST_A = 0xae,
    CAVE_ROLL_LIST_B = 0x81,
    CAVE_ROLL_SPELL = 0x63,
    CAVE_ROLL_EQUIPMENT = 0x5e,
    CAVE_ROLL_COMMON = 0x24,
    CAVE_DP_CHEST_KIND = 0x58,
    CAVE_DP_CHEST_BIT = 0x55,

    /* Room placement scratch: the next room's corner and the rectangle being
     * tried. */
    CAVE_DP_ROOM_WIDTH = 0x24,
    CAVE_DP_ROOM_HEIGHT = 0x25,
    CAVE_DP_ROOM_COLUMN = 0x26,
    CAVE_DP_ROOM_ROW = 0x27,
    CAVE_DP_FILL_ROOM = 0x54,
    CAVE_DP_ROOM_COUNT = 0x56,
    CAVE_DP_CURSOR_COLUMN = 0x5a,
    CAVE_DP_CURSOR_ROW = 0x5b,
    CAVE_DP_TALLEST_ROOM = 0x63,

    /* Neighbours of a cell in the 16-wide room grid. */
    CAVE_CELL_RIGHT = 1,
    CAVE_CELL_LEFT = -1,
    CAVE_CELL_DOWN = 0x10,
    CAVE_CELL_UP = -0x10,
    CAVE_CELL_UP_RIGHT = -0x0f,
    CAVE_CELL_UP_LEFT = -0x11,
    CAVE_CELL_DOWN_RIGHT = 0x11,
    CAVE_CELL_DOWN_LEFT = 0x0f,
    CAVE_CELL_LINKED = 0x40,
    CAVE_CELL_FLAGS = 0xc0,
    CAVE_CELL_ID_MASK = 0x3f,

    /* Room links: pairs of cells, ended by $FF, and the scratch list the
     * duplicate pass builds. */
    CAVE_LINKS = 0xe6f1,
    CAVE_LINK_SCRATCH = 0x0400,
    CAVE_LINK_MARK_A_LONG = 0x7fe6ad,
    CAVE_LINK_MARK_B_LONG = 0x7fe6ae,
    CAVE_DP_MERGE_PASSES = 0x2a,
    CAVE_DP_CELL_VALUE = 0x54,
    CAVE_DP_CORRIDOR_ID = 0x55,
    CAVE_DP_LINK_COUNT = 0x2d,
    CAVE_DP_LINK_INDEX = 0x5a,
    CAVE_DP_LINK_KEY = 0x54,
    CAVE_DP_SCRATCH_COUNT = 0x56,

    /* Cell positions in the 16-wide grid; the first row is the border. */
    CAVE_GRID_WIDTH = 0x10,
    CAVE_GRID_ROWS = 0x0e,
    CAVE_FIRST_ROOM_CELL = 0x10,
    CAVE_GRID_ROWS_END = 0xf0,
    CAVE_CELL_MARKED = 0x80,
    CAVE_BLANK_SHAPE = 0x1c,
    CAVE_BORDER_SHAPE_BASE = 0x33,
    CAVE_BORDER_SHAPES = 6,
    CAVE_SHAPE_TABLE = 0x93d59b,
    CAVE_LINK_SHAPE = 0x39,
    CAVE_LINK_BLOCK_ROW = 4,

    /* The hidden 2x2 treasure room and the objects and chests of ordinary
     * rooms. */
    CAVE_TREASURE_ROOM_ODDS = 0x10,
    CAVE_TREASURE_CELL_ODDS = 0x80,
    CAVE_TREASURE_LAST_CELL = 0xc0,
    CAVE_TREASURE_CELL = 0xe6a8,
    CAVE_TREASURE_MARK = 0xea,
    CAVE_TREASURE_OBJECTS = 13,
    CAVE_TREASURE_CHESTS = 8,
    CAVE_TREASURE_SPREAD = 8,
    CAVE_TREASURE_COLUMN_OFFSET = 1,
    CAVE_TREASURE_ROW_OFFSET = 3,
    CAVE_MIN_ROOM_OBJECTS = 4,
    CAVE_EXTRA_ROOM_OBJECTS = 4,
    CAVE_OBJECT_JITTER = 2,
    CAVE_MAX_CHESTS = 8,
    CAVE_DP_OBJECT_TARGET = 0x22,
    CAVE_DP_OBJECT_INDEX = 0x24,
    CAVE_DP_CHEST_ATTEMPTS = 0x59,
    CAVE_DP_NEIGHBOUR_BITS = 0x55,

    /* Block drawing: the decompressed block set at $7E:4000, the tile map in
     * bank $7F (a header, then two layers of 96-word rows) and the scratch
     * the passes below share. */
    CAVE_BLOCK_SET = 0xe699,
    CAVE_BLOCK_BUFFER = 0x4000,
    CAVE_BLOCK_BUFFER_LONG = WRAM_FIELD_MAP_ATTRIBUTES,
    CAVE_MAP_RESOURCE_LONG = 0x7fe69b,
    CAVE_MAP_BYTES = 0x7e1c,
    CAVE_MAP_LAYER_1 = 0x000a,
    CAVE_MAP_LAYER_2_HEADER = 0x3f0a,
    CAVE_MAP_LAYER_2 = 0x3f0e,
    CAVE_MAP_ROW_BYTES = 0xc0,
    CAVE_BLOCK_TILE_SPAN = 6,
    CAVE_MAP_ROW_SKIP = CAVE_MAP_ROW_BYTES - 2 * (CAVE_BLOCK_TILE_SPAN - 1),
    CAVE_TEMPLATE_A = 0x9f3f,
    CAVE_TEMPLATE_A_BYTES = 10,
    CAVE_TEMPLATE_B = 0x9f45,
    CAVE_TEMPLATE_B_BYTES = 4,
    CAVE_TILE_INDEX_MASK = 0x03ff,
    CAVE_TILE_FLAG_MASK = 0xfc00,
    CAVE_DP_RESOURCE = 0x54,
    CAVE_DP_RESOURCE_TARGET = 0x60,
    CAVE_DP_DRAW_CELL = 0x23,
    CAVE_DP_DRAW_COLUMNS = 0x26,
    CAVE_DP_DRAW_ROWS = 0x27,
    CAVE_DP_BLOCK_SHAPE = 0x22,

    /* Tile sets and decorations come from lists searched by key; each found
     * entry is read from $7E:F000 into eight-byte records at $7F:C000, one
     * 256-byte block per variant, the first block being the header (variant
     * count, then rows below the first). */
    CAVE_LIST_ENTRY_LONG = 0x7ef000,
    CAVE_LIST_TILE_SETS = 0x05,
    CAVE_LIST_DECORATIONS = 0x0a,
    CAVE_TILE_SET_KEY = 0x0a,
    CAVE_DECORATION_KEY = 0x04,
    CAVE_TILE_SET_COUNT = 4,
    CAVE_DECORATION_FIRST_SET = 3,
    CAVE_DECORATION_SETS = 5,
    CAVE_SET_TABLE = 0xc000,
    CAVE_SET_SIZE = 8,
    CAVE_SET_VARIANT_STRIDE = 0x100,
    CAVE_CELL_SET_MASK = 0x03,
    CAVE_DECORATION_ODDS = 0x30,
    CAVE_TILE_SET_WORDS_LONG = 0x000022,
    CAVE_DP_SET_OFFSET = 0x56,
    CAVE_DP_TILE_COUNT = 0x56,
    CAVE_DP_ROW_COUNT = 0x58,
    CAVE_DP_TILE_BITS = 0x54,
    CAVE_DP_EXTRA_ROWS = 0x5a,

    /* The finishing pass: link, stair and chest tiles, then the map sections. */
    CAVE_LINK_MARK_A = 0xe6ad,
    CAVE_LINK_MARK_B = 0xe6ae,
    CAVE_LINK_MARK_TILE = 0x4390,
    CAVE_STAIR_TILE = 0x4458,
    CAVE_CHEST_TILE = 0x474e,
    CAVE_CHEST_TILE_ITEM = 0x4754,
    CAVE_CHEST_ITEM_FLAG = 0x4000,
    CAVE_SECTION_COUNT = 0xd038,
    CAVE_SECTION_BYTES = 0x7e0e,
    CAVE_DP_SECTION_INDEX = 0x5d,
    CAVE_DP_SECTION_SIZE = 0x2d,
    CAVE_DP_SECTION_FLAGS = 0x28,

    CAVE_DP_TILE_COLUMN = 0x8f,
    CAVE_DP_TILE_ROW = 0x91,
};

#endif
